//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheet.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Employee
    {
        /**Instance variables**/
        LoginDatabaseEntities1 db = new LoginDatabaseEntities1();

        /**Properties**/
        public string Department { get; set; }
        public string Supervisor { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Mid_Name { get; set; }
        public int Banner_ID { get; set; }
        public string Name_Prefix { get; set; }
        public string Name_Suffix { get; set; }
        public string Job_Title { get; set; }
        public string FT_PT { get; set; }
        public string Faculty { get; set; }
        public string Email_Address { get; set; }
        public string Primary_Phone { get; set; }
        public string Secondary_Phone { get; set; }
        public string Campus { get; set; }
        public string Office { get; set; }
        public string Mailstop { get; set; }
        public string Display_Public { get; set; }
        public string Job_Desc_Number { get; set; }

        /**Default Constructor**/
        public Employee()
        {
            First_Name = "";
            Last_Name = "";
            Mid_Name = "";
            Banner_ID = 0;
            Name_Prefix = "";
            Name_Suffix = "";
            Job_Title = "";
            FT_PT = "";
            Faculty = "";
            Email_Address = "";
            Primary_Phone = "";
            Secondary_Phone = "";
            Campus = "";
            Mailstop = "";
            Display_Public = "";
            Job_Desc_Number = "";
        }

        /**all-arg Constructor**/
        public Employee(string fn, string ln, string mn, int bid, string np, string ns, string jt, string fp, string f, string em, string pp, string sp, string c, string m, string d, string jn)
        {
            First_Name = "";
            Last_Name = "";
            Mid_Name = "";
            Banner_ID = 0;
            Name_Prefix = "";
            Name_Suffix = "";
            Job_Title = "";
            FT_PT = "";
            Faculty = "";
            Email_Address = "";
            Primary_Phone = "";
            Secondary_Phone = "";
            Campus = "";
            Mailstop = "";
            Display_Public = "";
            Job_Desc_Number = "";
        }

        /**Method to obtain employee data from the database.Method accepts the
         * employee id as a paramter and returns an Employee object**/
        public Employee GetEmployee(int id)
        {
            var e = from employees in db.Employees
                    where employees.Banner_ID == id
                    select employees;
            Employee emp = (Employee)e.FirstOrDefault();
            return emp;
        }

        /**Method is to obtain employee data for multiple employees. Method accepts a supervisor
         * id as a parameter and returns a list of Employee objects**/
        public List<Employee> GetEmployees(string id)
        {
            List<Employee> empList = new List<Employee>();

            var emps = from employees in db.Employees
                       where employees.Supervisor == id
                       select employees;

            foreach (Employee e in emps)
            {
                empList.Add(e);
            }

            return empList;
        }
    }
}
