//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyReport
    {
        public int Id { get; set; }
        public string WeekEnding { get; set; }
        public Nullable<int> Banner_ID { get; set; }
        public string LeaveHours { get; set; }
        public string AdditionalHours { get; set; }
        public string HoursWorked { get; set; }
        public string TotalHoursWorked { get; set; }
        public string Overtime { get; set; }
        public string FLSA_Overtime { get; set; }
    }
}
